title: Kawehi Wang
location: "San Francisco, CA"
linkedin_url: https://www.linkedin.com/in/kawehi-w-3044b1199
gmail: kawehiwang2022@gmail.com
github_url: https://github.com/KawehiW

theme: jekyll-theme-minimal
